### ISSUE TITLE
Hard crash with isFinite and Symbol

### ISSUE THREAD

**Issue by METACEO** [jashkenas/underscore#2402]
Using:
* Node.js `v4.0.0`
* Underscore.js `1.8.3`
* and the code below...
```javascript
"use strict";

var _   = require('underscore');
var sym = Symbol();

console.log('sym',sym);

console.log(_.isFinite(sym));

```
...results with the following:
```
sym Symbol()
/test/node_modules/underscore/underscore.js:1242
    return isFinite(obj) && !isNaN(parseFloat(obj));
           ^

TypeError: Cannot convert a Symbol value to a number
    at isFinite (native)
    at Function._.isFinite (/test/node_modules/underscore/underscore.js:1242:12)
    at Object.<anonymous> (/test/test.js:8:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by G3E9** [comment]
The [line](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1314) in `underscore/underscore.js`.
